import Foundation
import SwiftData

@Model
class StationLog {
    var id: UUID = UUID()
    var stationId: String = ""
    var stationName: String? = nil
    var status: LogStatus = LogStatus.visited
    var timestamp: Date = Date()      // 旧フィールド（互換性のため残す）
    var createdAt: Date = Date()      // 記入日（自動記録、変更不可）
    var visitDate: Date? = nil        // 訪問日（ユーザーが任意で入力）
    var memo: String = ""
    var imageData: Data? = nil        // 写真データ（後方互換性のため残す）
    var imagesData: [Data] = []       // 複数写真データ（最大10枚）
    var tripId: UUID? = nil           // 経路ID（1つの経路内の駅をまとめる）
    var journeyId: UUID? = nil        // 旅ID（複数の経路をまとめる）
    var autoGenerated: Bool = false
    
    init(
        stationId: String,
        stationName: String? = nil,
        status: LogStatus,
        visitDate: Date? = nil,
        memo: String = "",
        imageData: Data? = nil,
        imagesData: [Data] = [],
        tripId: UUID? = nil,
        journeyId: UUID? = nil,
        autoGenerated: Bool = false
    ) {
        self.id = UUID()
        self.stationId = stationId
        self.stationName = stationName
        self.status = status
        self.timestamp = Date()
        self.createdAt = Date()
        self.visitDate = visitDate
        self.memo = memo
        self.imageData = imageData
        self.imagesData = imagesData
        self.tripId = tripId
        self.journeyId = journeyId
        self.autoGenerated = autoGenerated
    }

    // 全ての画像を取得（後方互換性のため、imageDataも含める）
    var allImages: [Data] {
        var images = imagesData
        if let singleImage = imageData, !images.contains(singleImage) {
            images.insert(singleImage, at: 0)
        }
        return images
    }
}

// ⚠️ LogStatusは別ファイル（LogStatus.swift等）で定義済みのため、ここでは定義しない
